PATHS:
  data_config_path: train/data
  data_root: dataset/openrooms # on cluster: /siggraphasia20dataset/code/Routine/DatasetCreation
  project_path: . # on cluster: /viscompfs/users/ruizhu/semseg
  data_root_cluster: /siggraphasia20dataset/code/Routine/DatasetCreation
  project_path_cluster: /viscompfs/users/ruizhu/semseg
  exp_name: pspnet50V2

DATA:
  dataset_name: 'openrooms'
  dataset_name_pred: 'openrooms'
  train_list: openrooms/list/train.txt
  val_list: openrooms/list/val.txt
  classes: 46
  if_remove_cls: False


TRAIN:
  arch: psp
  layers: 50
  sync_bn: True  # adopt syncbn or not
  train_h: 241
  train_w: 321
  resize: True
  resize_h: 240
  resize_w: 320
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 0
  aux_weight: 0.4
  # train_gpu: [0, 1, 2, 3]
  train_gpu: [0,1,2,3]
  workers: 16  # data loader workers
  batch_size: 32  # batch size for training
  batch_size_val: 32  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.01
  epochs: 200
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed:
  print_freq: 10
  save_freq: 1
  save_path: exp/openrooms/%s/model
  weight: 'none' # path to initial weight (default: none)
  resume: 'none' # path to latest checkpoint (default: none)
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  just_vis: False
  if_cluster: False
  val_every_iter: 3000
  save_every_iter: 3000
  train_in_nyu_label_space: False

Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

TEST:
  test_list: openrooms/list/test.txt
  test_has_gt: True
  test_in_nyu_label_space: False
  split: test  # split in [train, val and test]
  base_size: 2048  # based size for scaling
  resize_h_test: 240
  resize_w_test: 320
  test_h: 241
  test_w: 321
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: False  # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  test_gpu: [0]
  # model_path: exp/openrooms/%s/model/train_epoch_200.pth  # evaluation model path
  # save_folder: exp/openrooms/%s/result/epoch_200/val/ss  # results save folder
  model_path: exp/openrooms/pspnet50-2_cluster/train_epoch_46_tid_2909.pth  # evaluation model path
  save_folder: exp/openrooms/pspnet50-2_cluster/test_openrooms_results  # results save folder
  colors_path: openrooms/openrooms_colors.txt  # path of dataset colors
  names_path: openrooms/openrooms_names.txt  # path of dataset category names
