apiVersion: batch/v1
kind: Job
metadata:
  labels:
    user: rui
  name: zz-torch-job-gpu20220304-150618
  namespace: mc-lab
spec:
  backoffLimit: 2
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nautilus.io/group
                operator: In
                values:
                - haosu
              - key: gpu-type
                operator: In
                values:
                - 2080Ti
      containers:
      - args:
        - which python && . /root/miniconda3/etc/profile.d/conda.sh && conda activate
          /nityaagarwaldata/envs/py38 && which python && export TORCH_HOME=/nityaagarwaldata/
          && rclone --progress copy s3mm1:train/train-20220304-150618 /nityaagarwaldata/indoorInverse/job_list/train-20220304-150618
          && cd /nityaagarwaldata/indoorInverse/job_list/train-20220304-150618 &&
          /nityaagarwaldata/envs/py38/bin/python -m torch.distributed.launch --master_port
          5320 --nproc_per_node=2 trainBRDFLight.py --if_cluster --task_name 20220304-150618-train_POD_trainBRDF_scratch
          --if_train True --if_val True --if_vis True --eval_every_iter 5000 --if_overfit_train
          False DATASET.num_workers 14 MODEL_BRDF.enable True MODEL_BRDF.load_pretrained_pth
          False MODEL_BRDF.enable_BRDF_decoders True MODEL_BRDF.enable_list al_de_no_ro
          MODEL_BRDF.loss_list al_de_no_ro DATA.data_read_list al_de_no_ro DATA.im_height
          240 DATA.im_width 320 train_h 240 train_w 320 opt.cfg.DATASET.tmp False
          DEBUG.if_dump_perframe_BRDF True SOLVER.ims_per_batch 8 TEST.ims_per_batch
          8 DATA.load_brdf_gt True DATA.if_load_png_not_hdr False DATASET.mini False
          MODEL_BRDF.load_pretrained_pth False
        command:
        - sh
        - -c
        image: docker.io/jerrypiglet/rui_conda_inverse:public
        imagePullPolicy: IfNotPresent
        name: gpu-container-rui
        resources:
          limits:
            cpu: '30'
            memory: 50Gi
            nvidia.com/gpu: '2'
          requests:
            cpu: '15'
            memory: 20Gi
            nvidia.com/gpu: '2'
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /nityaagarwaldata
          name: nityaagarwaldatamclab
        - mountPath: /openroomsindept
          name: openroomsindept
      restartPolicy: Never
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
      - name: openroomsindept
        persistentVolumeClaim:
          claimName: openroomsindept
      - name: nityaagarwaldatamclab
        persistentVolumeClaim:
          claimName: nityaagarwaldatamclab
  ttlSecondsAfterFinished: 86400
