DATASET:
  num_workers: 16 
MODEL_BRDF:
  enable: False
MODEL_MATSEG:
  enable: True
  embed_dims: 16
DATA:
  data_read_list: ''
  im_height: 480
  im_width: 640
  if_load_png_not_hdr: True
  # load_brdf_gt: False
  load_masks: True
DEBUG:
  if_dump_perframe_BRDF: False
SOLVER:
  ims_per_batch: 6
TEST:
  ims_per_batch: 3